version: '2'
services:
  test_db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres 

  test_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: postgres
      DB_PASSWORD: postgres
    links:
      - test_db:postgres
    volumes:
      - .:/app
    command: ['/usr/bin/make', 'run-tests']


