version: '2'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres 

  api:
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_PASSWORD: postgres
    links:
      - db:postgres
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: ['python', 'examples/app.py']


